### PR TITLE
Add Auth to ERD

### PR DESCRIPTION
**Pull request by FoseFx**

### CODE REVIEW

**Comment by use-to** [comment]
This erd needs some changes. I guess the n-m-relationship of user and organization needs an seperate role according to the notes @JannikWibker sent to me. Also `organization_id` could be merged into the `emergency-room`-table.

**Review by use-to — CHANGES_REQUESTED** [review]
This erd needs some changes. I guess the n-m-relationship of user and organization needs an seperate role according to the notes @JannikWibker sent to me. Also `organization_id` could be merged into the `emergency-room`-table.

**Comment by FoseFx** [comment]
> I guess the n-m-relationship of user and organization needs an seperate role according to the notes @JannikWibker sent to me

No in v1 any user is an Admin of its org

> Also organization_id could be merged into the emergency-room-table.

Yes it is implemented this way in https://github.com/helpwave/rest-api/pull/102. In the ERD i think it makes more sense to have it there.

**Review by use-to — APPROVED** [review]

**Comment by use-to** [comment]
Maybe resolve these inconsistencies.

**Pull request merged**
